apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-jenkins

---

apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-volumes

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: kubernetes-volumes
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
